### ISSUE TITLE
Issue with Odml editor on Fedora

### ISSUE THREAD

**Issue by AkshayAgarwal007** [G-Node/odml-ui#1]
While executing the odml-gui.py on Fedora I am getting the following error:
```TypeError: pixbuf should be a GdkPixbuf```

which tracebacks to the following line:
https://github.com/G-Node/odml-ui/blob/master/odml/gui/Editor.py#L876

It works fine on Windows.

**Comment by gicmo** [comment]
Hi!

I just tried the editor on Fedora 25 and for me it seems to work. What version of Fedora are you running? Could you paste the complete traceback (if you have it). Is it starting at all for you, or is it crashing on some action?

**Comment by AkshayAgarwal007** [comment]
It's Fedora23. Odd... It's working fine now after a reboot. It was not starting at all at that time and was throwing the error I mentioned above. Sorry I don't have the complete traceback.
