### ISSUE TITLE
pip install odml installs v1.3.4 but odml-ui requires 1.4

### ISSUE THREAD

**Issue by jezekp** [G-Node/odml-ui#125]
![odml-install](https://user-images.githubusercontent.com/1769981/39353815-1c5ed8d8-4a09-11e8-8383-f992ef596007.png)

**Comment by mpsonntag** [comment]
Hi jezekp!
We are currently refactoring odml and odml-ui. Please install either both odml and odml-ui via pip. In this case you will receive both in compatible version 1.3.*. If you want to install the latest version 1.4 of odml-ui locally, please install both from source - [python-odml](https://github.com/G-Node/python-odml) using the current `master` branch and odml-ui using the current `development` branch.

Please let us know, if this solves your problem or if you need any further assistance!

**Comment by jezekp** [comment]
If I run sudo -H pip install odml-ui I get:

Requirement already satisfied: odml-ui in /usr/local/lib/python2.7/dist-packages/odML_UI-1.4.0-py2.7.egg (1.4.0)
Collecting odml>=1.4.* (from odml-ui)
  Could not find a version that satisfies the requirement odml>=1.4.* (from odml-ui) (from versions: 1.0, 1.1, 1.2, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4.1)
No matching distribution found for odml>=1.4.* (from odml-ui)

So it is actually the same result like before

**Comment by mpsonntag** [comment]
I think you need to uninstall the installed version of odml-ui and odml before you reinstall odml-ui via pip.
Or you install the current python-odml master from source, then the already installed odml-ui should work out of the box.

**Comment by jezekp** [comment]
You are right. I manually removed all old odml-ui files and now it works.

**Comment by mpsonntag** [comment]
By the way we will release the new version of odml and odml-ui fairly soon which will change minor parts of the file format and hopefully improve the overall handling of odml-ui. So keep your eyes out for new pip releases in the coming weeks if you stay interested in odml-ui.
