### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by jezekp** [G-Node/odml-ui#128]
After installing by sudo -H pip install odml-ui and running odmlui I'm getting the following warnings:

[Info] Conda check: Command 'conda info --json' returned non-zero exit status 127
[Warning] Icon odml-logo.png not found in supported paths
[Warning] Icon odml_addSection.png not found in supported paths
[Warning] Icon odml_addProperty.png not found in supported paths
[Warning] Icon odml_addValue.png not found in supported paths
[Warning] Icon odml_Dustbin.png not found in supported paths
[Warning] Icon INM6-compare-table.png not found in supported paths
[Warning] Icon INM6-convert-odml.png not found in supported paths
[Warning] Icon INM6-filter-odml.png not found in supported paths
[Warning] Icon INM6-merge-odml.png not found in supported paths
[Info] odMLTables not available: No module named odmltables

**Comment by mpsonntag** [comment]
I updated the icon search paths to include system wide and local user install as well as virtual environments. This should hopefully also fix the described problem.

These changes will be in the master branch once PR #130 is merged for an install from source, it might take a bit to make it into another `pip` release.
