### ISSUE TITLE
Enable linking of sections

### ISSUE THREAD

**Issue by jgrewe** [G-Node/odml-ui#13]
* links should only be allowed between sections that share the same type
* allow linking by dropping sections (indicate if link is possible, or not)

**Comment by achilleas-k** [comment]
Use a modifier for linking when dropping from a drag. Since we probably use CTRL for copy, linking should be ALT or CMD (macOS).
It could be ALT everywhere.

**Comment by achilleas-k** [comment]
Linking works but we decided to set the modifier to CTRL+SHIFT which seems to be a common default in file browsers.
