### ISSUE TITLE
Drag-and-Drop method fails for Property->Section drag action

### ISSUE THREAD

**Issue by digaru19** [G-Node/odml-ui#17]
@achilleas-k  @jgrewe  While fixing the Property->Section drag action, this issue cropped up again, in the Drag and Drop functionality.

The 'hacky' method we used (PR #5) does something like this :- 
Basically, each of '**Section_View**' widget and '**Property_View**' widget have their own '**DragProvider**' object. So, in our current method, we are attaching the **dnd_data** to the 'DragProvider' of the **source widget**, and on a 'drop', we look for the dnd_data in the **destination widget**. So, this method will work only if the source and destination widgets are same. Hence, we were able to drag sections within the 'Section_View' widget. 

But, drag between a 'Property_Widget' and a 'Section_Widget' fails because we attach the drag_data to the 'Property_Widget' and try to retrieve it from 'Section_Widget', which obviously fails.

To solve this issue, some solutions are :-
1) **Fix the original `Selection.set()` method**
 To fix this, I have a slight doubt on the method we use to create the drag targets' list in the **PropertyView** and **SectionView**. I think there is some internal magic that happens when we create a `target`, but which is abstracted by `pygtkcompat`, but later, while using `Selection.set()` method, it breaks. Maybe, if we start rewriting some part of that code, and if that is where the **real** cause of this issue is, we can fix this in a generic and safest way.

2) **Have something like a global `'DragData'` handler** (This works for _atleast_ Section->Section and Property->Section drags within the same window)
  This will function similar to what we are doing right now, but instead of attaching the data to the specific widget, we attach it to a global handler (global to an editor), which will respond to `'set_drag_data'` and `'get_drag_data'` kind of queries. We can customize this process completely to our own liking. But, one disadvantage of this method could be that, we might not be able to handle drags between two different instances of the editor window, as this handler remains local to an editor.

P.S. : We need to fix this to work on the section link functionalities, if we are relying on a _drag action_ for the linking (Issue #13) .

**Comment by achilleas-k** [comment]
I'd very much prefer the first approach, since it seems to be the *proper way*, so to speak, but if tracking down the cause of the issues there takes forever, I understand it's more realistic to use the second approach.

I'm curious: would the first approach allow dragging objects across different instances of the editor?

**Comment by digaru19** [comment]
Well, in the older editor (Python 2), dragging objects across different instances (windows) of the editor works well.
