### ISSUE TITLE
Integration of odml-tables from the UI

### ISSUE THREAD

**Issue by jgrewe** [G-Node/odml-ui#32]
(https://github.com/INM-6/python-odmltables)

have a menu (maybe tool bar buttons) for firing up odml-tables

**Comment by JuliaSprenger** [comment]
A first version of command line arguments are now supported by odMLtables ( see https://github.com/INM-6/python-odmltables/issues/8). These include starting a specific wizard from odMLtables main using the --wizard flag and optionally providing an input file using --file.

**Comment by mpsonntag** [comment]
Got a working solution for Python2 and a slightly updated version of odmltables. But I'm still trying to figure out how to deal with Python3.

**Comment by mpsonntag** [comment]
Resolved via #96 and #106.
