### ISSUE TITLE
Update setup.py

### ISSUE THREAD

**Issue by jgrewe** [G-Node/odml-ui#34]
this includes:
* dependencies (gtk stuff, odml-core, ...)
* Author/contributors
* description
* email
* hompage/url
* options for py2exe (if we are going to use it on windows)

**Comment by achilleas-k** [comment]
We would also like for `setup.py` to check for the external (non-python) dependencies and give an appropriate error with instructions when one is missing.

These should be `libgtk-3-0`and `gobject-introspection`. The python dependencies (`gi` or `gobject`) should be handled by pip itself.
