### ISSUE TITLE
setup.py incomplete

### ISSUE THREAD

**Issue by JuliaSprenger** [G-Node/odml-ui#44]
When installing via 'setup.py install' the odml-gui can not be run due to multiple errors:
- ImportError: cannot import name gi
- ImportError: cannot import name pygtkcompat

and potentially more errors...

**Comment by digaru19** [comment]
It is difficult (and sometimes unstable) to install the `gtk` dependencies directly, using the standard `setup.py install` procedure. So, we have not included it in the `setup.py` file.  
      Instead, we have listed the dependencies in the README file. It's better if these dependencies are installed using OS specific package managers (`apt`, `yum`, etc.).  
      I would suggest you start from either of `python3-gi` or `python-gi`, and if the installation is successful, you should be able to get the editor up and running. Else, you need to install the other dependencies too.

Regards

**Comment by JuliaSprenger** [comment]
In that case maybe it makes sense to include some example code on how these can be installed on the most common OS to make it simpler and less frustrating for beginners?

**Comment by digaru19** [comment]
Yeah, makes sense. We should have done that. Sorry for the inconvenience.  
  
 I will update the README soon, with example code snippets on how to install these packages.  
 For the time being, you can make use of the following packages for Ubuntu based OSs,  
- `sudo apt-get install libgtk-3-0` 
- `sudo apt-get install gobject-introspection`
- `sudo apt-get install python3-gi` (For Python 3)
- `sudo apt-get install python-gi` (For Python 2)
  
Do let us know if this works.

**Comment by mdenker** [comment]
Yes, help with installing the dependencies in the README would be very appreciated. In particular, if you know a way to install the dependencies (esp. gi) using anaconda environments, that would be great -- I didn't manage so far to get it working, but I'll post here in case I do...

**Comment by JuliaSprenger** [comment]
Hi again,
today I tried again to get the odml-ui running, unfortunately without success. The main issue is still python(3)-gi, which especially does not work in combination with conda environments. I tried to solve the issue as described here (https://stackoverflow.com/questions/37526026/how-to-install-gi-module-for-anaconda-python3) but I am still stuck at what seems to be a gi internal issue:

```
In [1]: import gi
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a23efdcdbcd8> in <module>()
----> 1 import gi

~/anaconda3/envs/odmlguipy3/lib/python3.6/site-packages/gi/__init__.py in <module>()
---> 42 from . import _gi

ImportError: cannot import name '_gi'
```
Do you have any ideas regarding this?


When you update the README, can stress that the dependencies listed above (libgtk etc) need to be installed in **addition** to what you describe as 'Installation'. 

Also, 'libglib2.0-dev' is listed twice as dependency.

**Update**
Here are the specifications I used: 
- Ubuntu 16.04, including
  - libffi-dev/xenial,now 3.2.1-4 amd64
  - libglib2.0-dev/xenial-updates,now 2.48.2-0ubuntu1 amd64
  - gobject-introspection/xenial,now 1.46.0-3ubuntu1 amd64
  - libgtk-3-dev/xenial-updates,now 3.18.9-1ubuntu3.3 amd64
  - python-gi/xenial,now 3.20.0-0ubuntu1 amd64
  - python3-gi/xenial,now 3.20.0-0ubuntu1 amd64

- anaconda version 1.6.3
- conda version 4.3.25, with environment
  - Python 3.6.2, including
  - certifi                   2016.2.28                py36_0  
  - decorator                 4.1.2                    py36_0  
  - ipython                   6.1.0                    py36_0  
  - ipython_genutils          0.2.0                    py36_0  
  - jedi                      0.10.2                   py36_2  
  - lxml                      4.1.1                     <pip>
  - openssl                   1.0.2l                        0  
  - path.py                   10.3.1                   py36_0  
  - pexpect                   4.2.1                    py36_0  
  - pickleshare               0.7.4                    py36_0  
  - pip                       9.0.1                    py36_1  
  - prompt_toolkit            1.0.15                   py36_0  
  - ptyprocess                0.5.2                    py36_0  
  - pygments                  2.2.0                    py36_0  
  - python                    3.6.2                         0  
  - readline                  6.2                           2  
  - setuptools                36.4.0                   py36_1  
  - simplegeneric             0.8.1                    py36_1  
  - six                       1.10.0                   py36_0  
  - sqlite                    3.13.0                        0  
  - tk                        8.5.18                        0  
  - traitlets                 4.3.2                    py36_0  
  - wcwidth                   0.1.7                    py36_0  
  - wheel                     0.29.0                   py36_0  
  - xz                        5.2.3                         0  
  - zlib                      1.2.11                        0  

... and gi manually added as described above.

However, I don't think the exact specifications cause the issue since I do get the same error using a python2 environment.

**Comment by mpsonntag** [comment]
Ideally for anaconda environments we find the required GObject introspection libraries from a conda package manager and pre-install them in the conda environment before installing via `setup.py`.

**Comment by mpsonntag** [comment]
So far I have identified the following dependencies from the anaconda cloud service:

```
conda install -c conda-forge pygobject
conda install -c conda-forge atk
conda install -c conda-forge pango
conda install -c conda-forge gdk-pixbuf
```

But I'm still missing the `Gdk` library.

**Comment by mpsonntag** [comment]
Got odml-ui running in conda environments by installing these following libraries in the following order:
```
conda install -c pkgw/label/superseded gtk3
conda install -c conda-forge pygobject
conda install -c conda-forge gdk-pixbuf
```
odml-ui works fine, but there still are issues displaying the proper icons.

**Comment by JuliaSprenger** [comment]
Thanks! I managed to get odml-ui installed. However, the installation as described above fails when gi is only added as a link to the site-packages and not copied. How did you handle this?

**Comment by JuliaSprenger** [comment]
Is it possible to add a desktop icon when installing via the setup.py? This might get confusing when using different conda environments with different installations, but maybe this can be optional?
